### ISSUE TITLE
Issue page header and Focus Area header hides search

### ISSUE THREAD

**Issue by lizzycederberg** [Threespot/aldf-wp#155] opened 2018-06-22 16:26 UTC
When on an issue page (e.g. https://live-aldf-wp.pantheonsite.io/issue/animals-in-entertainment/) or focus area page (e.g. https://live-aldf-wp.pantheonsite.io/focus_area/farmed-animals/) if you click Search the field is hidden: https://live-aldf-wp.pantheonsite.io/issue/animals-in-entertainment/

![screen shot 2018-06-22 at 12 24 40 pm](https://user-images.githubusercontent.com/13699106/41787786-7e59da44-7617-11e8-96d3-ba6f749d1c5f.png)

---
Checklist:
- 🔗  Provide links to affected pages
- 💁  Describe the issue and any steps required to reproduce it
- 📷  Include a screenshot or video of the problem
- 💻  List all versions of affected browsers and operating systems
- 🚩  Apply any relevant labels

**Comment by tedw** [comment] 2018-06-22 16:36
@lizzycederberg This is not related to any specific post type. If you resize the browser it will be fixed.

I thought this was only happening locally due to the way Browsersync injects CSS changes. I didn't realize this had happened on the live site. Will look into it.

**Comment by tedw** [comment] 2018-06-22 17:23
I think I fixed this but I couldn’t reliably reproduce the issue in the first place so hard to say 100%.

LMK if you still see this issue and I can implement a more drastic fix.

**Comment by tedw** [comment] 2018-06-22 17:52
Ready for testing

**Comment by lizzycederberg** [comment] 2018-06-22 19:08
Ok I tested the same pages in Chrome, FF, and Safari (if that matters), and I'm not seeing it anywhere. I will keep it open for now in case I see it again, but I think it's ok. 

CC @lfrancis Just a heads up in case you see this.

**Comment by tedw** [comment] 2018-06-29 01:49
The previous two commits should have solved this issue once and for all. Was a very weird bug I hadn't encountered before. Apparently, adding a JS file in the `<head>` set to `defer` causes any CSS styles with `transition` applied to transition from the default browser user-agent styles to whatever was defined in the CSS. This caused the expandable JS to miscalculate the height of the container, preventing it from expanding fully.

**Closed** 2018-07-06 19:19 UTC
